### ISSUE TITLE
Blank pages in new Paperback version

### ISSUE THREAD

**Issue by neyako** [Huynh12345678/Extensions-Viet#2]
Error HTTP 403 if use Legacy Reader, just blank when use new reader in new Paperback update. It's happened for all of sources in repo.

![D181E7F7-31EB-4298-99F8-85197372D0B5](https://user-images.githubusercontent.com/64780385/172476919-f03d7a37-2c68-4dda-bcbc-829325b68e30.png)
![CA471675-381A-4CDC-A282-67EE41772E91](https://user-images.githubusercontent.com/64780385/172476938-813e6fda-f6ec-4717-8508-2b789480848e.png)

**Comment by Huynh12345678** [comment]
> Error HTTP 403 if use Legacy Reader, just blank when use new reader in new Paperback update. It's happened for all of sources in repo.
> 
> ![D181E7F7-31EB-4298-99F8-85197372D0B5](https://user-images.githubusercontent.com/64780385/172476919-f03d7a37-2c68-4dda-bcbc-829325b68e30.png) ![CA471675-381A-4CDC-A282-67EE41772E91](https://user-images.githubusercontent.com/64780385/172476938-813e6fda-f6ec-4717-8508-2b789480848e.png)


This error has been fixed 😁
