### ISSUE TITLE
Bản mới từ Appstore bị lỗi ạ

### ISSUE THREAD

**Issue by qnehihi** [Huynh12345678/Extensions-Viet#4]
bản tải từ appstore lỗi không dùng được extensions Viet ạ
link appstore: https://apps.apple.com/vn/app/paperback-a-komga-client/id1626613373?l=vi&platform=iphone

**Comment by Huynh12345678** [comment]
Đã fix 🤣🤣🤣

**Comment by Huynh12345678** [comment]
> bản tải từ appstore lỗi không dùng được extensions Viet ạ link appstore: https://apps.apple.com/vn/app/paperback-a-komga-client/id1626613373?l=vi&platform=iphone

Đã fix 🤣🤣🤣

**Comment by qnehihi** [comment]
> > bản tải từ appstore lỗi không dùng được extensions Viet ạ link appstore: https://apps.apple.com/vn/app/paperback-a-komga-client/id1626613373?l=vi&platform=iphone
> 
> Đã fix 😉

mà acc voz của bác bây giờ là gì thế
